jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t khulnasoft-dash:${CIRCLE_SHA1} .
      - run:
          name: Login to Khulnasoft registry and pull scanner
          command: docker login registry.khulnasoft.com -u ${KHULNASOFT_USER} -p ${KHULNASOFT_PASSWORD} && docker pull registry.khulnasoft.com/scanner:5.3
      - run:
          name: Scan image with Khulnasoft scanner
          command: docker run -e BUILD_JOB_NAME=${CIRCLE_BUILD_URL} -e BUILD_NUMBER=${CIRCLE_BUILD_NUM} --rm -v /var/run/docker.sock:/var/run/docker.sock registry.khulnasoft.com/scanner:5.3 scan --host=${KHULNASOFT_CONSOLE} --user=${KHULNASOFT_SCANNER_USER} --password=${KHULNASOFT_SCANNER_PASSWORD} --no-verify --verbose-errors --local khulnasoft-dash:${CIRCLE_SHA1}
      - run:
          name: Push image to DockerHub 
          command: |
            echo "PUT PUSH HERE - docker push [OPTIONS] NAME[:TAG]"
workflows:
  version: 2
  release:
    jobs:
      - build:
          context:
            - khulnasoft
